spring:
  application:
    name: hello-dubbo-consumer

dubbo:
  scan:
    base-packages: com.grady.apache.dubbo.consume.controller
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://172.16.5.132:8848

server:
  port: 8080

endpoints:
  dubbo:
    enabled: true
management:
  health:
    dubbo:
      status:
        defaults: memory
        extras: threadpool
  endpoints:
    web:
      exposure:
        include: "*"