spring:
  application:
    name: hello-dubbo-provider

dubbo:
  scan:
    base-packages: com.grady.apache.dubbo.provider.service.impl
  protocol:
    name: dubbo
    port: 20880
  provider:
    loadbalance: roundrobin
  registry:
    address: nacos://172.16.5.132:8848